name: Chisel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Scala
      uses: olafurpg/setup-scala@v10

    - name: Build
      run: sbt "runMain main.VerilogMain"
    - name: Run riscv-tests
      run: |
        bash ./test.sh
